### PR TITLE
End of Life for stigfix Project

### PR DESCRIPTION
**Pull request by shawndwells**
Given that SCAP Security Guide is now shipping natively in RHEL, this patch drops legacy code and creates a README pointing to the SCAP Security Guide project.

### CODE REVIEW

**Comment by fcaviggia** [comment]
Shawn, I was thinking this over - I still would like to keep the configuration management and some of the toggle switches. Please give me a call and we'll talk it over.

**Comment by shawndwells** [comment]
On 2/6/15 12:37 PM, Frank Caviggia wrote:
> Shawn, I was thinking this over - I still would like to keep the 
> configuration management and some of the toggle switches. Please give 
> me a call and we'll talk it over.
Part of the idea of a Pull Request is to give the community a voice in 
the conversation... a voice which may say this project is needed, or a 
voice that says go ahead and EOL. Calls don't give the community a voice 
in the conversation.

Configuration management is better placed in Puppet, Satellite, or even 
Cockpit. Why would we want bash scripts to do *any* config management?

Also, why keep a project that duplicates the upstream remediation scripts?

What value is there to stig-fix these days?

**Comment by fcaviggia** [comment]
Shawn, there are voices that you aren't listening to - including several people within Red Hat. I've looked over a number of the kickstarts that have been put out that totally miss the mark on deployment in a standalone environment and what's actually required in the field.  SSG has a lot of good aspects, but as of right now, it's not feature complete. I'll try test a newer version here this weekend and if I'm satisfied I'll be more than happy comply with your request.

**Comment by jason-callaway** [comment]
There's already a community around this project, and many users I know personally.  The users and contributors are free to "vote with their feet" and use SSG, Puppet, or whatever else they like.  But EOL-ing a popular project just invites forking (the bad kind).

Frank, I vote to reject this PR.

**Comment by shawndwells** [comment]
On 2/7/15 10:34 PM, Jason Callaway wrote:
>
> There's already a community around this project, and many users I know 
> personally. The users and contributors are free to "vote with their 
> feet" and use SSG, Puppet, or whatever else they like. But EOL-ing a 
> popular project just invites forking (the bad kind).
>
> Frank, I vote to reject this PR.
>

Here's the thing:  *this project is the fork*. This project goes against 
NIST, NSA, DoD, and broader US Government initiatives. This project goes 
against RHT strategy. This project serves as a distraction and fractures 
the community.

stig-fix was approved to provide STIG remediation scripts until RHEL 
began shipping content. RHEL now provides such content natively via the 
SCAP Security Guide.

What specific need(s) does continued existence of this project serve?

**Comment by jason-callaway** [comment]
> What specific need(s) does continued existence of this project serve?

This project excels at one thing: STIGing RHEL through rpm.  Use of rpm is just for convenience.  There will continue to be demand for this project until some other tool can apply STIG settings easily and reliably.

> This project goes against NIST, NSA, DoD, and broader US Government initiatives. This project goes against RHT strategy.

(There's no way for me to put this without it sounding flamey, take it however you like. If your feelings are hurt, I'll buy you a beer.)

Those statements are matters of opinion. You don't speak for the US Government, nor are you an arbiter of Red Hat strategy. I'm aware of no official Red Hat statement anathematizing this project. Sources authored by yourself don't count. The RHEL 6 STIG itself explicitly permits alternative software in section 2.2:

"If alternate software is used to provide a function ordinarily provided by a default system application, the specific check and fix information for that function is no longer valid. The SA or the reviewer is responsible for evaluating the requirements based on documentation available for the alternate software."

Note that alternate software is not disallowed.

So long as 1) stig-fix-el6 is not illegal and 2) people want to use it, I see no reason to EOL the project.

[0] - http://iase.disa.mil/stigs/os/unix-linux/Pages/index.aspx

**Comment by shawndwells** [comment]
On 2/8/15 2:23 AM, Jason Callaway wrote:
>
>     What specific need(s) does continued existence of this project serve?
>
> This project excels at one thing: STIGing RHEL through rpm. Use of rpm 
> is just for convenience. There will continue to be demand for this 
> project until some other tool can apply STIG settings easily and reliably.
>

We ship an RPM natively in RHEL that performs these functions. So again, 
why continue fracturing efforts?

>     This project goes against NIST, NSA, DoD, and broader US
>     Government initiatives. This project goes against RHT strategy.
>
> (There's no way for me to put this without it sounding flamey, take it 
> however you like. If your feelings are hurt, I'll buy you a beer.)
>
> Those statements are matters of opinion. You don't speak for the US 
> Government,
>
They are not opinion, and the Government speaks for the Government. 
Suggest a reading of the STIG review:
http://people.redhat.com/swells/rhel6stig/U_RedHat_6_V1R5_Overview.pdf

 From Section 1.1:
The consensus content was developed using an open-source project called 
SCAP Security Guide. The project’s website is 
https://fedorahosted.org/scap-security-guide/. Except for differences in 
formatting to accommodate the DISA STIG publishing process, the content 
of the RHEL6 STIG should mirror the SCAP Security Guide content with 
only minor divergence as updates from multiple sources work through the 
consensus process.

SSG is the upstream of the DoD STIG, NIST USGCB, NSA's CS2, CIA's C2S, 
NRO's CSCF, and many others.

The DISA SCAP strategy started in 2010:
http://www.disa.mil/news/conferences-and-events/~/media/files/disa/news/conference/cif/briefing/ia_stig_scap_and_data_metrics.pdf

Converting things to SCAP became an official task in 2011:
http://www.disa.mil/News/Conferences-and-Events/Customer-and-Industry-Forum-2011/~/media/Files/DISA/News/Conference/2011/Operate-and-Assure/Automating_STIGs_sherald_customer_conference.ppt 
(ref pg4)

The GSA SCAP strategy is being pushed through formal requirements via 
the CDM program, which is being pushed to all civilian agencies. I 
couldn't find the later editions of the CDM technical requirements, nor 
one from a .gov, but here are the CDM Technical Requirements:
http://www.thecre.com/cm/wp-content/uploads/2012/06/DHF.Draft_Technical_Requirements.pdf

A few examples:
> 97 5. Meeting Security Content Automation Protocol (SCAP) and 
> relational requirements for
> 98 interoperability of reporting (dashboard, query, etc.).
> 99 a. If the tool doesn’t have a relational database (DB), extract the 
> data to a provided
> 100 relational DB.
> 101 b. If the tool doesn’t support SCAP, use a program provided by the 
> government to convert
> 102 the relational data to SCAP.
> 103 c. If the tool only supports SCAP, use a tool provided by the 
> government to convert the
> 104 SCAP data to a relational DB. 

And:
> CM-F-5.1: Receive and provide configuration data (i.e., communicate 
> with the central dashboard and
> 1144 other components) using standard interfaces and formats, where 
> applicable, to the extent that such
> 1145 standards can be applied with acceptable network performance and 
> reasonable data storage limits.
> 1146 c. [must] Use a relational data structure [to be defined].
> 1147 d. [should] Use XML-based SCAP standard parameters. The tool 
> [may] do this in SCAP
> 1148 version 1.2 or later (i.e., Extensible Configuration Checklist 
> Definition Format [XCCDF], Open Vulnerability Assessment Language [OVAL®
> 1149 ], Open Checklist Interactive Language [OCIL], CCE™, and Common 
> Platform Enumeration [CPE™])30
> 1150 or other
> 1151 suitable language.
> 1152 e. [should] Process configuration data and distribute them using 
> the CCE™ standard
> 1153 version 5 or newer.
> 1154 f. [should] Report assessment results using XCCDF version 1.2 or 
> later XCCDF Results
> 1155 Format Schema.
> 1156 g. [should] Encapsulate assessment results using Asset Reporting 
> Format (ARF) version 1.1
> 1157 or later.
> 1158 h. [should] use NIST-specified open standards such as: Asset 
> Summary Report (ASR)
> 1159 protocol (an emerging specification) or CPE™ version 2.3 or 
> later, to express and
> 1160 communicate configuration information


> nor are you an arbiter of Red Hat strategy.
>
For US Government standards and baselines, I am. That'd be my full time 
job, actually ;)

> I'm aware of no official Red Hat statement anathematizing this 
> project. Sources authored by yourself don't count. The RHEL 6 STIG 
> itself explicitly permits alternative software in section 2.2:
>
> "If alternate software is used to provide a function ordinarily 
> provided by a default system application, the specific check and fix 
> information for that function is no longer valid. The SA or the 
> reviewer is responsible for evaluating the requirements based on 
> documentation available for the alternate software."
>
> Note that alternate software is not disallowed.
>

https://yourlogicalfallacyis.com/strawman ;)

I never said it was disallowed. I said it was against broader intent and 
strategy. And because of this, I inquire what reason(s) exist to continue.


> So long as 1) stig-fix-el6 is not illegal and 2) people want to use 
> it, I see no reason to EOL the project.
>
> [0] - http://iase.disa.mil/stigs/os/unix-linux/Pages/index.aspx
>

People wanted to continue using their Commodore 65's too.

There was extreme value in Aqueduct, the project these scripts forked 
from. We needed to mash things together a certain way, which is how 
stig-fix came along. The intent was to open source hardening scripts 
that RHT staff were using until something, someday, shipped natively in 
RHEL.

That something/someday is the present, which is driving a reflection on 
if stig-fix should still be maintained. The arguments seem to reflect a 
lack of understanding on existing capabilities. *If* I understand the 
arguments (on- and off-list):

/- The desire to version STIG baslines via RPM./
Accomplished via scap-security-guide, now shipping natively in RHEL

/- The desire to run independent checks, not an entire STIG scan./
Accomplished via OpenSCAP --xccdf-id, --id, or --oval-id

/- The desire to tailor / adjust / create exceptions/
Accomplished by SCAP drift files [CLI] or via SCAP Workbench [GUI] which 
uses check boxes on selecting/deselecting controls and their refine 
values. Output is saved with hashes and in RPM format.

/- The desire to checkpoint systems/
SCAP Security Guide does not do this, nor should it. Checkpoints are a 
backup/recovery feature best left to configuration management tools (not 
automation content). Puppet, Satellite, etc are where such functionality 
belongs. This checkpoint mentality was also driven by needing to apply 
STIGs post-deployment of RHEL. With things now being STIG'd natively 
(and not as bolt on bash scripts), this seems less important. But maybe 
there is a use case I'm missing here.

The existence of this project is in duplication with the remediation 
scripts being  developed by the STIG community and shipped natively in 
the STIG itself. If there are bugs in the native remediation scripts, 
why not fix them versus fork? Why not open bugs? Why would we want to 
maintain a fork via stig-fix that duplicates an entire project?

There may be very valid reasons to such questions and this is an attempt 
to pull them out through discussion.

**Comment by shawndwells** [comment]
Also, forgot about this earlier: on 18-DEC we merged most (all?) of the actual STIG remediations into SSG and removed them from stig-fix:

https://github.com/RedHatGov/stig-fix-el6/pull/32

**Comment by shawndwells** [comment]
Had a RHT internal call. Agreed to sunset the project within 90 days. Will send a PR to update the README shortly.

**Pull request closed without merging**
